# Generated by Django 3.0 on 2021-06-18 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20210617_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='diarista',
            name='cidade',
            field=models.CharField(default='Antes', max_length=50, verbose_name='Cidade'),
        ),
    ]
